### ISSUE TITLE
Adding more functionality in ops libraries.

### ISSUE THREAD

**Issue by neesingh-rh** [srijan-sivakumar/redant#135]
Add functionalities to ops libraries along with the test cases to verify them.
1. In io_ops:- rmdir for removing directories and file_exist function to check if a file exists or not
2. In peer_ops:-  nodes_from_pool_list and get_pool_list for retrieving the nodes in the pool

**Comment by srijan-sivakumar** [comment]
Hi @neesingh-rh , can you modify the issue description to define as to what functionality is being added.

**Comment by neesingh-rh** [comment]
> Hi @neesingh-rh , can you modify the issue description to define as to what functionality is being added.

Okay.

**Comment by srijan-sivakumar** [comment]
Closing this issue as we have to modularly track issues rather than a simple issue saying `add more functionality`.

**Comment by srijan-sivakumar** [comment]
@nishith-vihar @neesingh-rh @aujjwal-redhat . Take this as a consideration. Vague issue names and descriptions are not a good indicator and would lead to confusion to the reviewers. Start creating issues specific to tasks which are directed towards some functional addition and one can understand the feature right from the issue being fixed/added and the description before even moving to the code.
