### ISSUE TITLE
Enhancing the config file

### ISSUE THREAD

**Issue by nishith-vihar** [srijan-sivakumar/redant#150]
mount information in the config file has to be removed and servers allocated to the volumes have to be removed

**Comment by srijan-sivakumar** [comment]
Also moving it to /config from /core/parsing

**Comment by nishith-vihar** [comment]
host name field has to be added in the servers info

**Comment by nishith-vihar** [comment]
Config file is simplified to clients info,servers info and volume types. Parsing module should be changed accordingly.
