### ISSUE TITLE
Rexe: Changing over to passwordless ssh

### ISSUE THREAD

**Issue by srijan-sivakumar** [srijan-sivakumar/redant#154]
The current flow expects password to be provided but it'd be better if passwordless ssh is made norm in the connection from the host to other servers and clients.

**Comment by srijan-sivakumar** [comment]
The current decision is to take up for fedora 32 specific machines as base and to see why ssh is failing in fedora 33. @aujjwal-redhat , please take this to completion.

**Comment by aujjwal-redhat** [comment]
After a certain level of experimentation, it was founded that Fedora 33 is not able to provide a green flag for public-key authentication in Paramiko. Tested the same code on Fedora 32 gave a success message.
