### ISSUE TITLE
Volume creation from parent TC based on config.

### ISSUE THREAD

**Issue by srijan-sivakumar** [srijan-sivakumar/redant#186]
The current TC flow doesn't give much automated feature for handling a TC. Technically a user shouldn't have to decide for how a volume is to be created but rather what type of volume and how many servers to be used for it.

The proposal is to handle it in the manner mentioned in the doc : [Volume Ops](https://docs.google.com/document/d/1K9Fuy8uP7LjUfZkajwzPVFBroZiW1uX5BF9c1pbVKvM/edit?usp=sharing)

**Comment by srijan-sivakumar** [comment]
- [ ] Volume name to be taken from the testcase name and the volume type. Hence if the test case is `test_sample.py`, and of the type of volume for which it is being executed is `dist` then the name of the volume which'll be created will be `test_sample_dist`.
- [ ] Getting the server and brick details from the config file and hence the user doesn't have to pass the details on their own. Also, passing the volume options dictionary to the volume_create rather than having a kwars arrangement. This is two prong, a) Kwargs might consume more time and has more changes of exceptions and errors in runtime if not handled properly. b) The volume options being passed will be the one read from the config file and if the user doesn't override it with their own custom options then the default config will be used for creating the volume.
- [ ] We also need to track the volumes being created for a given TC. Hence a dictionary test_vol_dict will be passed on as an argument to the volume_create function which will add the volume details once it is successfully created. This same dictionary will come handy in deciding various other operations such as brick add, delete, replace, mount volume, unmount volume, volume cleanup/delete.
- [ ] A separate function called volume cleanup which will go through this said test_vol_list to to clean the test cluster. This is useful if we want the framework to handle the vol unmount, snap unmount,  snap deletion, vol stop, vol delete, brick cleanup etc in one single function.  This function will be available alongside the volume_stop and volume_delete.
- [ ] After the above operations are being handled properly introduce the dynamic selection of bricks. The current approach will name the bricks as per the volume and server name combination with a count. But if there are more than one brick root dirs then it'll be required to balance the brick dir creation across these given set of brick roots.
- [ ] It is not at all important to provide where to run many a gluster specific commands if they're part of a cluster. Hence the node to run the command can be left to the framework also.

**Comment by nik-redhat** [comment]
> * [ ]  Volume name to be taken from the testcase name and the volume type. Hence if the test case is `test_sample.py`, and of the type of volume for which it is being executed is `dist` then the name of the volume which'll be created will be `test_sample_dist`.
Naming like `test_sample-dist` would be better to distinguish between function name and vol type.

> * [ ]  We also need to track the volumes being created for a given TC. Hence a dictionary test_vol_dict will be passed on as an argument to the volume_create function which will add the volume details once it is successfully created. This same dictionary will come handy in deciding various other operations such as brick add, delete, replace, mount volume, unmount volume, volume cleanup/delete.
Why do we need to track the volumes being created?

> * [ ]  A separate function called volume cleanup which will go through this said test_vol_list to to clean the test cluster. This is useful if we want the framework to handle the vol unmount, snap unmount,  snap deletion, vol stop, vol delete, brick cleanup etc in one single function.  This function will be available alongside the volume_stop and volume_delete.
Like a teardown function? Isn't that already implemented or we don't have tests doing any such operation now?

> * [ ]  It is not at all important to provide where to run many a gluster specific commands if they're part of a cluster. Hence the node to run the command can be left to the framework also.

It should be optional. If not provided then it will compute else, the user should be able to provide the servers to run the command manually as well.

**Comment by BarakSason** [comment]
>     * [ ]  Volume name to be taken from the testcase name and the volume type. Hence if the test case is `test_sample.py`, and of the type of volume for which it is being executed is `dist` then the name of the volume which'll be created will be `test_sample_dist`.

In addition to the composition of the volname, similar composition is required at the brick level, with one extra prefix, which will indicate the brick number (e.g. test_sample_dist_brick_1)
 
>     * [ ]  Getting the server and brick details from the config file and hence the user doesn't have to pass the details on their own. Also, passing the volume options dictionary to the volume_create rather than having a kwars arrangement. This is two prong, a) Kwargs might consume more time and has more changes of exceptions and errors in runtime if not handled properly. b) The volume options being passed will be the one read from the config file and if the user doesn't override it with their own custom options then the default config will be used for creating the volume.

A class (or hashmap, depending how the intefrace API will be designed) called something like vol_options (whose values are parsed from the config file) should be instantiated and passed to the test during initialization. 
Did not fully understand the comments about the Kwargs or how is it relevant here.

>     * [ ]  We also need to track the volumes being created for a given TC. Hence a dictionary test_vol_dict will be passed on as an argument to the volume_create function which will add the volume details once it is successfully created. This same dictionary will come handy in deciding various other operations such as brick add, delete, replace, mount volume, unmount volume, volume cleanup/delete.

The only case we need to track volume creations from within the test is if the test creates an additional volume in addition to its "default" one. A simple linked list is sufficient here.

>     * [ ]  A separate function called volume cleanup which will go through this said test_vol_list to to clean the test cluster. This is useful if we want the framework to handle the vol unmount, snap unmount,  snap deletion, vol stop, vol delete, brick cleanup etc in one single function.  This function will be available alongside the volume_stop and volume_delete.

We haven't gotten there yet, but the cleanup part is very important.
It's the responsibility of each TEST and *NOT* the framework to perform cleanup. Cleanup should take place in the "terminate" part of the test. In case the test created additional volumes, these should be cleaned as well.
The only 2 things the is the framework's responsibility in regards to cleanup are:
1 - Cluster deletion
2 - In case the user forcefully terminated the current execution (e.g. CTRL + C), the framework should include a signal handler which will trigger a cleanup to all resources. NOTHING should remain, even if the framework was forcefully terminated.

>     * [ ]  After the above operations are being handled properly introduce the dynamic selection of bricks. The current approach will name the bricks as per the volume and server name combination with a count. But if there are more than one brick root dirs then it'll be required to balance the brick dir creation across these given set of brick roots.

Yes. Already addressed this as part of the 1st point.

>     * [ ]  It is not at all important to provide where to run many a gluster specific commands if they're part of a cluster. Hence the node to run the command can be left to the framework also.

I presented the randomization reasoning a couple of sessions ago. At that time the implementation of the solution was very naive - a more complex mechanism is already in place and we need to go over it.

**Comment by srijan-sivakumar** [comment]
Initial part of the issue handled. More volume types to be added, plus other points to be covered in iteration 3.
