### ISSUE TITLE
Adding a mechanism to exclude specific tests

### ISSUE THREAD

**Issue by srijan-sivakumar** [srijan-sivakumar/redant#207]
A flag is to be added so that test_list builder doesn't go ahead and add it in the test runs. This is useful for tests not considered suitable to be run because of a BUG or due to some other valid reason.

**Comment by srijan-sivakumar** [comment]
@nishith-vihar add a doc link explaining the design decision taken here. This is an important feature from the user perspective while being run by the user.

**Comment by BarakSason** [comment]
Based on the discussion on the approach, I believe the name of this issue should be changed to "Adding a mechanism to exclude tests"

**Comment by nishith-vihar** [comment]
@BarakSason Ack
