### ISSUE TITLE
Requirement of `cmd run successfully` in all operations.

### ISSUE THREAD

**Issue by srijan-sivakumar** [srijan-sivakumar/redant#250]
This seems like an overkill. Even though the improvement received might be in small units, it is but a logical step to not log for successful run of a command. The reasoning being just stating running command xyz on node or nodes xyz without showing any errors for the same command, will imply that it succeeded, hence we can eliminate these success logs.

**Comment by BarakSason** [comment]
I disagree with the statement "just stating running command xyz on node or nodes xyz without showing any errors for the same command, will imply that it succeeded" - There are numerous cases in which an error can occur without actually being propagated back (simplest example is deadlock on the server which will cause prevent the command result from even returning), in these case, without specifically logging a success/failure, it'd be impossible to determine success with 100% certainty.
