### ISSUE TITLE
Why to send redant from parent_test

### ISSUE THREAD

**Issue by aujjwal-redhat** [srijan-sivakumar/redant#267]
In parent test.py we are already initializing self.redant the mixin object 
```bash
 def _configure(self, mname: str, server_details: dict,
                   client_details: dict, log_path: str, log_level: str):
        machine_detail = {**client_details, **server_details}
        self.redant = RedantMixin(machine_detail)
        self.redant.init_logger(mname, log_path, log_level)
        self.redant.establish_connection()
```

Then why are we providing it as an arg if we are already extending it 
```bash
            self.mountpoint, self.client_list[0])
            self.run_test(self.redant)
```

**Comment by nishith-vihar** [comment]
Yeah I think even i noticed it. In test case you can refer the functions either by redant.function() or self.redant.function()

**Comment by srijan-sivakumar** [comment]
Yeah, that was done deliberately to save us all from the annoying `self.redant`. Functionally it provides no extra features. `self.redant` and `redant` are both one and the same.
