### ISSUE TITLE
Migrate test_add_brick_when_quorum_not_met

### ISSUE THREAD

**Issue by nik-redhat** [srijan-sivakumar/redant#352]
Migrate the TC [test_add_brick_when_quorum_not_met](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_add_brick_when_quorum_not_met.py)

**Comment by nik-redhat** [comment]
Passing it on to you @aujjwal-redhat . Hope that's fine.

**Comment by aujjwal-redhat** [comment]
Yeah np @nik-redhat :+1:
