### ISSUE TITLE
Logging messages to follow the required format

### ISSUE THREAD

**Issue by aujjwal-redhat** [srijan-sivakumar/Redant#42]
### Log Message format
===================
All log messages MUST include:
* The cmd that is/was executed
* The machine(s) on which the command is/was executed

Ex: peer_ops

On starting the execution of cmd on a node:
```js
 self.rlog("Running %s on node %s" % (cmd,node), 'I')
```
On completing the execution:
```js
 self.rlog("Successfully ran %s on %s " % (cmd, node),'I')
```
### Log levels
===========

* Everything in the ops library has to be in info mode.
* Everything in the test cases has to be in error mode.
* Everything other than ops to be in debug mode.

**Comment by aujjwal-redhat** [comment]
@srijan-sivakumar @BarakSason Do verify it, please.

**Comment by srijan-sivakumar** [comment]
@aujjwal-redhat , this design decision can be added in the logging.md so that it is documented.

**Comment by aujjwal-redhat** [comment]
Ok

**Comment by srijan-sivakumar** [comment]
Let's keep this open till the relevant patches are merged.
