### ISSUE TITLE
[TEST] Migration of test_volume_status_with_absent_bricks

### ISSUE THREAD

**Issue by neesingh-rh** [srijan-sivakumar/redant#465]
Migrate test case:[test_volume_status_with_absent_bricks](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_status_with_absent_bricks.py)

**Comment by aujjwal-redhat** [comment]
This test case is merged already. Apparently, instead of updates, fixes should have been used. Hence, closing this issue manually.
