### ISSUE TITLE
Using formatted string literals.

### ISSUE THREAD

**Issue by srijan-sivakumar** [srijan-sivakumar/redant#50]
The usual way of formatting string in python had been
`("sample %s" %(val) )` or `("sample %s", val)`

But the cleaner way of doing it is using the formatted strings.
`(f"sample {val}")`. I propose we use this format across the project rather than having multiple different ways of formatting our string.

For reference : https://docs.python.org/3.6/reference/lexical_analysis.html#formatted-string-literals

**Comment by nik-redhat** [comment]
I was just going to open a discussion on the same topic :p . I agree with this, and let's follow one approach, whichever is cleaner.

**Comment by srijan-sivakumar** [comment]
Yes..The formatted string approach reduces the code length and is also not a sore sight for eyes as compared to other formats. One can easily understand as to what would be logged easily.

**Comment by aujjwal-redhat** [comment]
Yeah let's make a standards.md file and put these format rules. It's hard to just go through the issues.

**Comment by nik-redhat** [comment]
> I think we need to document these python code level considerations in a doc as standards. Just issues might be hard to refer to..

+1
