### ISSUE TITLE
Pylint specific errors and the messages

### ISSUE THREAD

**Issue by aujjwal-redhat** [srijan-sivakumar/redant#89]
### E1101:
'%s %r has no %r member%s'
https://pycodequ.al/docs/pylint-messages/e1101-no-member.html

In our code
### E1101:  :x:
Instance of 'VolumeOps' has no 'rlog' member (no-member)

### E0401: :x:
Unable to import 'redant_libs.support_libs.rexe' (import-error)

### R0801: :x:
Similar lines in 5 files

### R0903: :x:
Too few public methods (0/2) (too-few-public-methods)

### C0103: :x:
Variable name "f" doesn't conform to snake_case naming style (invalid-name)

### W0703:  :x:
Catching too general exception Exception (broad-except)

### R0902: :x:
Too many instance attributes (12/7) (too-many-instance-attributes)

## Regerating the errors locally :

1. Remove the specific errors or all of them from disable in .pylintrc file. 
2. Then run the command:

```js
pylint -j 4 --rcfile=.pylintrc redant_libs/
```

**Comment by aujjwal-redhat** [comment]
### What to do with this?
We can remove the specific ones locally and run pylint.
Remove the errors in case it appears to be an error.
If it is a warning then it can be skipped.
Push the changes and put a tick for them in this issue.

**Comment by srijan-sivakumar** [comment]
Converting to a discussion as it is ingrained now to follow pylint.
